name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true

    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v2.4.8
      with:
        hugo-version: "latest"
        extended: true

    - name: Build
      run: hugo
      extended: true

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        external_repository: sachit-menon/sachit-menon.github.io
        deploy_key: ${{ secrets.MACBOOK_GITHUB_KEY }}
        publish_dir: ./public
        user_name: 'github-actions[bot]'
        user_email: 'github-actions[bot]@users.noreply.github.com'